version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpswd
       MYSQL_DATABASE: ${DB_DATABASE}
       MYSQL_USER: ${DB_USERNAME}
       MYSQL_PASSWORD: ${DB_PASSWORD}
     ports:
       - '${DB_PORT}:3306'

   redis:
     image: 'bitnami/redis:latest'
     environment:
       - REDIS_PASSWORD=${REDIS_PASSWORD}
     ports:
       - '${REDIS_PORT}:6379'
volumes:
    db_data: {}
